export const projects = {
  Code: [
    { title: 'OSA: Observational\nSpatiotemporal Anomaly Detector', 
      subtitle: 'a modular framework for weakly supervised abnormality detection in paediatric echocardiographic video', 
      tag: 'Python - PyTorch', 
      github: 'https://github.com/cashmurb/OSA-' },
    { title: 'Rainbow-lite Deep Q-Learning on MsPacman', 
      subtitle: 'A python implementation of a Rainbow-lite DQN agent trained on Ale/MsPacman-v5.', 
      tag: 'Python 3.x - PyTorch - Numpy - Gymnasium + ALE-Py - OpenCV', 
      github: 'https://github.com/cashmurb/rainbow-lite-ms-pacman' },
    { title: 'iPod Music Player', 
      subtitle: 'A desktop music player app widget inspired by the classif iPod design.', 
      tag: 'JavaScript - Electron - CSS - HTML', 
      github: 'https://github.com/cashmurb/ipod-music-player' },
    { title: 'BnB Booking and Management Platform', 
      subtitle: 'A web platform for booking and managing BnB properties.', 
      tag: 'Next.js 16 - Supabase - Vercel - Resend - Google Gemini API', 
      github: 'https://github.com/cashmurb/bnb-booking-platform' },
    null, null,
  ],
  Film: [null, null, null],
  Photo: [null, null, null],
};
